<%@ Page Language="C#" AutoEventWireup="true" CodeFile="ImportPage.aspx.cs" Inherits="ImportPage" %>


<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        <asp:FileUpload ID="buttonChooseFile" runat="server" />
        <add name = "constr" connectionString = "Data Source=.\MainDB;Database=MainDB;User Id=mudassar;password=xxxxx"/>
    
    </div>
        <asp:GridView ID="GridViewTruong" runat="server" AutoGenerateColumns="False" DataKeyNames="TenTruongHoc" DataSourceID="SourceDB" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
            <Columns>
                <asp:BoundField DataField="TenTruongHoc" HeaderText="TenTruongHoc" ReadOnly="True" SortExpression="TenTruongHoc" />
                <asp:BoundField DataField="Website" HeaderText="Website" SortExpression="Website" />
                <asp:BoundField DataField="DienThoai" HeaderText="DienThoai" SortExpression="DienThoai" />
                <asp:BoundField DataField="QuyMo" HeaderText="QuyMo" SortExpression="QuyMo" />
                <asp:BoundField DataField="SoLuong" HeaderText="SoLuong" SortExpression="SoLuong" />
                <asp:BoundField DataField="CapNhatLuc" HeaderText="CapNhatLuc" SortExpression="CapNhatLuc" />
                <asp:BoundField DataField="KhuVuc" HeaderText="KhuVuc" SortExpression="KhuVuc" />
                <asp:BoundField DataField="SoLop12" HeaderText="SoLop12" SortExpression="SoLop12" />
                <asp:BoundField DataField="TongGiamThi" HeaderText="TongGiamThi" SortExpression="TongGiamThi" />
                <asp:BoundField DataField="DienThoaiTongGiamThi" HeaderText="DienThoaiTongGiamThi" SortExpression="DienThoaiTongGiamThi" />
                <asp:BoundField DataField="EmailTongGiamThi" HeaderText="EmailTongGiamThi" SortExpression="EmailTongGiamThi" />
                <asp:BoundField DataField="DKDT2013" HeaderText="DKDT2013" SortExpression="DKDT2013" />
                <asp:BoundField DataField="TrungTuyen2013" HeaderText="TrungTuyen2013" SortExpression="TrungTuyen2013" />
                <asp:BoundField DataField="NhapHoc2013" HeaderText="NhapHoc2013" SortExpression="NhapHoc2013" />
                <asp:BoundField DataField="DiaChi" HeaderText="DiaChi" SortExpression="DiaChi" />
                <asp:BoundField DataField="TinhTP" HeaderText="TinhTP" SortExpression="TinhTP" />
                <asp:BoundField DataField="QuanHuyen" HeaderText="QuanHuyen" SortExpression="QuanHuyen" />
                <asp:BoundField DataField="PhuongXa" HeaderText="PhuongXa" SortExpression="PhuongXa" />
                <asp:BoundField DataField="GhiChu" HeaderText="GhiChu" SortExpression="GhiChu" />
                <asp:BoundField DataField="HieuTruong" HeaderText="HieuTruong" SortExpression="HieuTruong" />
                <asp:BoundField DataField="DienThoaiHieuTruong" HeaderText="DienThoaiHieuTruong" SortExpression="DienThoaiHieuTruong" />
                <asp:BoundField DataField="EmailHieuTruong" HeaderText="EmailHieuTruong" SortExpression="EmailHieuTruong" />
                <asp:BoundField DataField="DiaChiHieuTruong" HeaderText="DiaChiHieuTruong" SortExpression="DiaChiHieuTruong" />
                <asp:BoundField DataField="PhoHieuTruong" HeaderText="PhoHieuTruong" SortExpression="PhoHieuTruong" />
                <asp:BoundField DataField="DienThoaiPhoHieuTruong" HeaderText="DienThoaiPhoHieuTruong" SortExpression="DienThoaiPhoHieuTruong" />
                <asp:BoundField DataField="EmailPhoHieuTruong" HeaderText="EmailPhoHieuTruong" SortExpression="EmailPhoHieuTruong" />
                <asp:BoundField DataField="DiaChiPhoHieuTruong" HeaderText="DiaChiPhoHieuTruong" SortExpression="DiaChiPhoHieuTruong" />
                <asp:BoundField DataField="BiThuDoanTruong" HeaderText="BiThuDoanTruong" SortExpression="BiThuDoanTruong" />
                <asp:BoundField DataField="DienThoaiBiThuDoanTruong" HeaderText="DienThoaiBiThuDoanTruong" SortExpression="DienThoaiBiThuDoanTruong" />
                <asp:BoundField DataField="EmailBiThuDoanTruong" HeaderText="EmailBiThuDoanTruong" SortExpression="EmailBiThuDoanTruong" />
                <asp:BoundField DataField="DiaChiBiThuDoanTruong" HeaderText="DiaChiBiThuDoanTruong" SortExpression="DiaChiBiThuDoanTruong" />
                <asp:BoundField DataField="PhoHieuTruong2" HeaderText="PhoHieuTruong2" SortExpression="PhoHieuTruong2" />
                <asp:BoundField DataField="DienThoaiPhoHieuTruong2" HeaderText="DienThoaiPhoHieuTruong2" SortExpression="DienThoaiPhoHieuTruong2" />
                <asp:BoundField DataField="EmailPhoHieuTruong2" HeaderText="EmailPhoHieuTruong2" SortExpression="EmailPhoHieuTruong2" />
                <asp:BoundField DataField="DiaChiPhoHieuTruong2" HeaderText="DiaChiPhoHieuTruong2" SortExpression="DiaChiPhoHieuTruong2" />
                <asp:BoundField DataField="ChuTichHoiPHHS" HeaderText="ChuTichHoiPHHS" SortExpression="ChuTichHoiPHHS" />
                <asp:BoundField DataField="DienThoaiChuTichHoiPHHS" HeaderText="DienThoaiChuTichHoiPHHS" SortExpression="DienThoaiChuTichHoiPHHS" />
                <asp:BoundField DataField="EmailChuTichHoiPHHS" HeaderText="EmailChuTichHoiPHHS" SortExpression="EmailChuTichHoiPHHS" />
                <asp:BoundField DataField="DiaChiChuTichHoiPHHS" HeaderText="DiaChiChuTichHoiPHHS" SortExpression="DiaChiChuTichHoiPHHS" />
                <asp:BoundField DataField="NguoiPhuTrach" HeaderText="NguoiPhuTrach" SortExpression="NguoiPhuTrach" />
                <asp:BoundField DataField="ChucVu" HeaderText="ChucVu" SortExpression="ChucVu" />
                <asp:BoundField DataField="DienThoaiNguoiPhuTrach" HeaderText="DienThoaiNguoiPhuTrach" SortExpression="DienThoaiNguoiPhuTrach" />
                <asp:BoundField DataField="EmailNguoiPhuTrach" HeaderText="EmailNguoiPhuTrach" SortExpression="EmailNguoiPhuTrach" />
                <asp:BoundField DataField="ThongTinMieuTa_UuTienLienLac" HeaderText="ThongTinMieuTa_UuTienLienLac" SortExpression="ThongTinMieuTa_UuTienLienLac" />
                <asp:BoundField DataField="DKDT2014" HeaderText="DKDT2014" SortExpression="DKDT2014" />
                <asp:BoundField DataField="TrungTuyen2014" HeaderText="TrungTuyen2014" SortExpression="TrungTuyen2014" />
                <asp:BoundField DataField="NhapHoc2014" HeaderText="NhapHoc2014" SortExpression="NhapHoc2014" />
                <asp:BoundField DataField="XetTuyen2015" HeaderText="XetTuyen2015" SortExpression="XetTuyen2015" />
                <asp:BoundField DataField="NhapHoc2015" HeaderText="NhapHoc2015" SortExpression="NhapHoc2015" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="SourceDB" runat="server" ConnectionString="<%$ ConnectionStrings:MainDB %>" OnSelecting="SqlDataSource1_Selecting" SelectCommand="SELECT * FROM [Truong]"></asp:SqlDataSource>
        <asp:Button ID="buttonUpload" runat="server" Text="Upload" OnClick="buttonUpload_Click" />
        <asp:Button ID="buttonExportPDF" runat="server" OnClick="buttonExportPDF_Click" Text="Report PDF" />
    </form>
</body>
</html>
